### ISSUE TITLE
Error happens if not connected to our company network in DiscourseRestApi.cs

### ISSUE THREAD

**Issue by justinzhaoa** [AaronYFQ/Dior#15]
Errors in DiscourseRestApi.cs line 132
System.Net.WebException: 'The remote name could not be resolved: 'discourse.lmera.ericsson.se''

**Comment by AaronYFQ** [comment]
add exception handling in the funtion, and add a local variable in ThisAddin.cs
discourseServerConnected, and the according Getter, IsDiscourseServerConnected. When user click the ribbon buttone, please check this value first, If it's false, need prompt user to connect to ENC and restart the outlook to enable the Addin.

**Comment by justinzhaoa** [comment]
add checking in Dior/Dior/RibbonDior.cs
merged in:
[https://github.com/AaronYFQ/Dior/commit/231718bc26824880294cf7edb7189de0ff9c8c32](https://github.com/AaronYFQ/Dior/commit/231718bc26824880294cf7edb7189de0ff9c8c32)
