### ISSUE TITLE
Error happens when parsing Skype saved mails

### ISSUE THREAD

**Issue by justinzhaoa** [AaronYFQ/Dior#19]
Errors in MailParseAction line 161

System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Comment by AaronYFQ** [comment]
Update as below to check the Sender, for Exchange email, it's always not null, for SMTP type mail, it will be empty.

            //when mail is "SMTP" type it means mail from non-exchanger user, always use current user
            if (mail.Sender != null && mail.Sender.GetExchangeUser() != null)
            {
                firstMailEntry.sender = mail.SenderName;
                firstMailEntry.senderAddressAndAlias = new MailAddressAndAlias(mail.Sender.GetExchangeUser().PrimarySmtpAddress, mail.Sender.GetExchangeUser().Alias);
            }
