### ISSUE TITLE
How to handle if the account it not a discourse user? [Zheng]

### ISSUE THREAD

**Issue by AaronYFQ** [AaronYFQ/Dior#2]

**Comment by zchen2016** [comment]
I try to test the account which is not a discourse user by using curl command. Actually, it **CANNOT** create a new ticket by using the account which is not a discourse user.

If the add in just used within MJE developers frequently, we can ignore the account which is not a discourse user. Another way is to detect the account first, if it not a discourse user, we can use a common account to create the ticket.

**Comment by AaronYFQ** [comment]
OK. Great. Then we can use the poster to represent it for the topic. close the issue now.
