### ISSUE TITLE
MailParse issue: wrong includes the mail subject in every mail body

### ISSUE THREAD

**Issue by justinzhaoa** [AaronYFQ/Dior#22]
-----------------------------------
Mail list | Sender: Zheng Chen A
Mail list | Address: justin.a.zhao@ericsson.com
Mail list | Alias: edfhiin
Mail list | Date: 6/22/2017 1:44:00 PM
Mail list | body:  RE: Pre-study summary about outlook addin for summer campHi, AaronPlease add me in the project in github:Username: zchen2016Email：19871014chen@163.com“Dior” is a perfect name!!!Thanks,Zheng Chen
-----------------------------------
-----------------------------------
Mail list | Sender: Justin Zhao A
Mail list | Address: justin.a.zhao@ericsson.com
Mail list | Alias: edfhiin
Mail list | Date: 6/22/2017 10:39:00 AM
Mail list | body:  RE: Pre-study summary about outlook addin for summer campHi Aaron,Please add me in the project in github:Username: justinzhaoaEmail: zhaojianjun111@163.comDior is nice name.--Best Regards!Justin Zhao
-----------------------------------
-----------------------------------
Mail list | Sender: Aaron Yu
Mail list | Address: justin.a.zhao@ericsson.com
Mail list | Alias: edfhiin
Mail list | Date: 6/21/2017 1:19:00 PM
Mail list | body:  Pre-study summary about outlook addin for summer campIn short, it’s feasible from technical view. Another good news is that we can simulate other persons to create a historic topic and post!!!, even the create date can be past dateJ1. Tried to setup an outlook Addin in VSTO 2017 community version, deploy and install it on outlook. It works well. Means no special privilege needed;2. I have run curl to test the Rest API provide by discourse,// get categories, OKcurl -k -X GET https://discourse.lmera.ericsson.se/categories.json// get tags by a category id, OK, here 9 is the id of MJEcurl -k -X GET https://discourse.lmera.ericsson.se/9.json// In sandbox, create a topic as myself OK,curl -k -X POST &quot;https://discourse.lmera.ericsson.se/posts&quot; -H &quot;Content-Type: multipart/form-data;&quot; -F &quot;api_key=562ac764a6f559f7e245ff5378b70055b1b51af61b3fa2ac0ccbf9f8ff4b72fb&quot; -F &quot;api_username=efaqiyu&quot; -F &quot;title=test from outlook 3 efaqiyu&quot; -F &quot;raw=it's first try from test api&quot; -F &quot;category=5&quot; -F &quot;created_at=2017-06-23&quot;// In sandbox, create a post to reply the topic above OK, with another person’s id, for example, echnzhe.curl -k -X POST &quot;https://discourse.lmera.ericsson.se/posts&quot; -H &quot;Content-Type: multipart/form-data;&quot; -F &quot;api_key=562ac764a6f559f7e245ff5378b70055b1b51af61b3fa2ac0ccbf9f8ff4b72fb&quot; -F &quot;api_username=echnzhe&quot; -F &quot;topic_id=35055&quot; -F &quot;raw=this is a reply from zhaojie chen&quot; -F &quot;created_at=2017-06-233. I create an empty project in github.com, we can use it for version control, just like what we are doing everyday. If you have no Github account, please create one. After I add your account in the project, we can start then.4. At last, most of important, about the name, so far I have a candidate , “Dior” J, “Discourse In Outlook Ribbon”, Ribbon is the official conception of Addin in outlook in VSTO. What we will do in Outlook is actually implement functions in the Ribbon.Br,Aaron
-----------------------------------

**Comment by AaronYFQ** [comment]
solved.
