### ISSUE TITLE
how to parse mails to topics 

### ISSUE THREAD

**Issue by AaronYFQ** [AaronYFQ/Dior#7]

**Comment by zchen2016** [comment]
The format of Email is as following: HTML/Rich Text/Plain Text.
First, I do some research of translating HTML to Plain Text format and parse email header.

**Comment by zchen2016** [comment]
hi, I find an class named MailMessage Class in MSDN, it contains MailMessage.Headers Property which could get the e-mail headers that are transmitted with this email message.
Namespace:   System.Net.Mail
Assembly:  System (in System.dll)
https://msdn.microsoft.com/en-us/library/system.net.mail.mailmessage.headers%28v=vs.110%29.aspx

-     Bcc
- 
-     Cc
- 
-     Content-ID
- 
-     Content-Location
- 
-     Content-Transfer-Encoding
- 
-     Content-Type
- 
-     Date
- 
-     From
- 
-     Importance
- 
-     MIME-Version
- 
-     Priority
- 
-     Reply-To
- 
-     Sender
- 
-     To
- 
-     X-Priority

**Comment by AaronYFQ** [comment]
closed as already implemented with regex
